### ISSUE TITLE
ModuleNotFoundError: No module named 'clock'

### ISSUE THREAD

**Issue by KenMacD** [opacam/Cohen3#16]
Installing the latest version using:

    pip install https://github.com/opacam/Cohen3/archive/master.zip

will fail with:

```
  Downloading https://files.pythonhosted.org/packages/a2/37/f46636488468b8c30d7a59be471fdd9fb84b82ca3d770fe819e815bec65d/eventdispatcher-1.81.tar.gz
    ERROR: Complete output from command python setup.py egg_info:
    ERROR: Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "/tmp/pip-install-dvxm4cem/eventdispatcher/setup.py", line 4, in <module>
        from eventdispatcher import __version__
      File "/tmp/pip-install-dvxm4cem/eventdispatcher/eventdispatcher/__init__.py", line 12, in <module>
        from .scheduledevent import ScheduledEvent
      File "/tmp/pip-install-dvxm4cem/eventdispatcher/eventdispatcher/scheduledevent.py", line 8, in <module>
        from clock import Clock
    ModuleNotFoundError: No module named 'clock'
    ----------------------------------------
ERROR: Command "python setup.py egg_info" failed with error code 1 in /tmp/pip-install-dvxm4cem/eventdispatcher/
```

**Comment by opacam** [comment]
Well, this is strange :thinking: ...I just tried to install Cohen3 in my system and it works fine for me, you can see my terminal output in here:

```
opacam@DEPOBOX:~$ pip3 install https://github.com/opacam/Cohen3/archive/master.zip --user
Collecting https://github.com/opacam/Cohen3/archive/master.zip
  Downloading https://github.com/opacam/Cohen3/archive/master.zip (555kB)
     |████████████████████████████████| 563kB 241kB/s 
Requirement already satisfied: ConfigObj>=4.3 in ./.local/lib/python3.7/site-packages (from Cohen3==0.9.1) (5.0.6)
Requirement already satisfied: Twisted>=18.7 in ./.local/lib/python3.7/site-packages (from Cohen3==0.9.1) (18.9.0)
Requirement already satisfied: zope.interface in ./.local/lib/python3.7/site-packages (from Cohen3==0.9.1) (4.6.0)
Requirement already satisfied: lxml in ./.local/lib/python3.7/site-packages (from Cohen3==0.9.1) (4.3.3)
Requirement already satisfied: eventdispatcher in ./.local/lib/python3.7/site-packages (from Cohen3==0.9.1) (1.9.4)
Requirement already satisfied: python-dateutil in ./.local/lib/python3.7/site-packages (from Cohen3==0.9.1) (2.8.0)
Requirement already satisfied: pyopenssl in ./.local/lib/python3.7/site-packages (from Cohen3==0.9.1) (19.0.0)
Requirement already satisfied: six in /usr/lib/python3/dist-packages (from ConfigObj>=4.3->Cohen3==0.9.1) (1.12.0)
Requirement already satisfied: constantly>=15.1 in ./.local/lib/python3.7/site-packages (from Twisted>=18.7->Cohen3==0.9.1) (15.1.0)
Requirement already satisfied: Automat>=0.3.0 in ./.local/lib/python3.7/site-packages (from Twisted>=18.7->Cohen3==0.9.1) (0.7.0)
Requirement already satisfied: hyperlink>=17.1.1 in ./.local/lib/python3.7/site-packages (from Twisted>=18.7->Cohen3==0.9.1) (18.0.0)
Requirement already satisfied: incremental>=16.10.1 in ./.local/lib/python3.7/site-packages (from Twisted>=18.7->Cohen3==0.9.1) (17.5.0)
Requirement already satisfied: attrs>=17.4.0 in ./.local/lib/python3.7/site-packages (from Twisted>=18.7->Cohen3==0.9.1) (19.1.0)
Requirement already satisfied: PyHamcrest>=1.9.0 in ./.local/lib/python3.7/site-packages (from Twisted>=18.7->Cohen3==0.9.1) (1.9.0)
Requirement already satisfied: setuptools in ./.local/lib/python3.7/site-packages (from zope.interface->Cohen3==0.9.1) (41.0.1)
Requirement already satisfied: numpy in ./.local/lib/python3.7/site-packages (from eventdispatcher->Cohen3==0.9.1) (1.16.2)
Requirement already satisfied: future in ./.local/lib/python3.7/site-packages (from eventdispatcher->Cohen3==0.9.1) (0.17.1)
Requirement already satisfied: cryptography>=2.3 in /usr/lib/python3/dist-packages (from pyopenssl->Cohen3==0.9.1) (2.6.1)
Requirement already satisfied: idna>=2.5 in /usr/lib/python3/dist-packages (from hyperlink>=17.1.1->Twisted>=18.7->Cohen3==0.9.1) (2.6)
Building wheels for collected packages: Cohen3
  Building wheel for Cohen3 (setup.py) ... done
  Stored in directory: /home/opacam/.tmpdir/pip-ephem-wheel-cache-1uldyziw/wheels/1a/c4/84/4c6dad00e43aa1c4edbc666aeea4a43a933c4fe4c4b906c848
Successfully built Cohen3
Installing collected packages: Cohen3
  Found existing installation: Cohen3 0.9.0
    Uninstalling Cohen3-0.9.0:
      Successfully uninstalled Cohen3-0.9.0
Successfully installed Cohen3-0.9.1
opacam@DEPOBOX:~$ pip3  --version
pip 19.1.1 from /home/opacam/.local/lib/python3.7/site-packages/pip (python 3.7)
```

Seeing your command I noticed that you tried to install it using `pip`, if you take a look on the above output you will see that I used `pip3`, I did that way because, in my system, `pip` triggers the install for python2 (it's still the default and `Cohen3` it's only python3) but you may have changed that in your OS. You can verify which python will be trigered with the command `pip --version`, for instance...

here is mine for `pip3`:
```
opacam@DEPOBOX:~$ pip3  --version
pip 19.1.1 from /home/opacam/.local/lib/python3.7/site-packages/pip (python 3.7)
```

And for `pip` I get:
```
opacam@DEPOBOX:~$ pip --version
pip 19.1.1 from /home/opacam/.local/lib/python2.7/site-packages/pip (python 2.7)
```

So...It Could be  that you are trying to install  `Cohen3` for python2?

**Note:** I would recommend you to do an user install, so the command it would be: `pip3 install https://github.com/opacam/Cohen3/archive/master.zip --user`

**Comment by KenMacD** [comment]
From your log you're using an already installed `eventdispatcher` version `1.9.4`.

Unfortunately if you don't have that project already installed then `pip` will decide that the latest version is `1.81`, even though that version is 2 years older than the actual latest version of `1.9.4`.

I opened #17 to specify a version directly. `< 1.10` would also likely work if you like that more.

**Comment by opacam** [comment]
Good caught @KenMacD :smile:, **thanks** for the investigation and the pull request :+1:

already merged in master branch :wink:
