### ISSUE TITLE
Cohen3 uses HTTPPageGetter which has been removed from Twisted

### ISSUE THREAD

**Issue by ilveroluca** [opacam/Cohen3#45]
Cohen3 won't start with a recent version of Twisted because it uses the Twisted HTTPPageGetter API which has been [removed for security reasons](https://twistedmatrix.com/trac/ticket/10295).

```
$ cohen3 -h
Traceback (most recent call last):
  File "/usr/local/bin/cohen3", line 5, in <module>
    from coherence.cli import main
  File "/usr/local/lib/python3.9/site-packages/coherence/cli.py", line 27, in <module>
    from coherence.base import Coherence, Plugins
  File "/usr/local/lib/python3.9/site-packages/coherence/base.py", line 71, in <module>
    from coherence.upnp.core.device import Device, RootDevice
  File "/usr/local/lib/python3.9/site-packages/coherence/upnp/core/device.py", line 32, in <module>
    from coherence.upnp.core import utils
  File "/usr/local/lib/python3.9/site-packages/coherence/upnp/core/utils.py", line 611, in <module>
    class myHTTPPageGetter(client.HTTPPageGetter):
  File "/usr/local/lib/python3.9/site-packages/twisted/python/deprecate.py", line 475, in __getattribute__
    value = getattr(state._module, name)
AttributeError: module 'twisted.web.client' has no attribute 'HTTPPageGetter'
```

**Comment by ilveroluca** [comment]
For the moment, this can issue can be worked around be requiring `twisted = ">=20.3.0,<22"`.

**Comment by opacam** [comment]
:+1:  Thanks for reporting!!

For now, we pinned twisted version at PR #43

**Comment by pataquets** [comment]
Forgive my newbieness but, might this have something to do with #41?
