### ISSUE TITLE
AttributeError: module 'collections' has no attribute 'MutableMapping'

### ISSUE THREAD

**Issue by richstokes** [opacam/Cohen3#67]
```
/Users/rich/Library/Python/3.11/bin/cohen3
Traceback (most recent call last):
  File "/Users/rich/Library/Python/3.11/bin/cohen3", line 5, in <module>
    from coherence.cli import main
  File "/Users/rich/Library/Python/3.11/lib/python/site-packages/coherence/cli.py", line 27, in <module>
    from coherence.base import Coherence, Plugins
  File "/Users/rich/Library/Python/3.11/lib/python/site-packages/coherence/base.py", line 62, in <module>
    from eventdispatcher import (
  File "/Users/rich/Library/Python/3.11/lib/python/site-packages/eventdispatcher/__init__.py", line 5, in <module>
    from .dictproperty import DictProperty, ObservableDict
  File "/Users/rich/Library/Python/3.11/lib/python/site-packages/eventdispatcher/dictproperty.py", line 13, in <module>
    class ObservableDict(collections.MutableMapping):
                         ^^^^^^^^^^^^^^^^^^^^^^^^^^
AttributeError: module 'collections' has no attribute 'MutableMapping'
```

**Comment by opacam** [comment]
Thank you for bringing this issue to our attention!

I wanted to let you know that I'm fully aware of this error. It occurs in Python versions greater than 3.9 due to a change in the attribute `MutableMapping` from the collections module, which has been moved to collections.abc in Python 3.10. It's important to note that our dependency, `eventdispatcher`, is one of the triggers for this error. However, it's not the only one. The testing framework we use, nose, also relies on `MutableMapping`.

To address this, I've taken the initiative of fixing the problem by creating a fork of `eventdispatcher` [(eventdospatcher3)](https://github.com/opacam/eventdispatcher3) where this issue has been resolved. Additionally, we're planning to eliminate our dependency on nose since it's no longer actively maintained. I've already started the process by initiating Pull Request (#66) to tackle these changes. However, please be aware that resolving this issue may take some time.

Once again, I appreciate your patience and understanding. We're actively working towards resolving this error and making the necessary adjustments to ensure smooth functionality in **Python versions beyond 3.9**. If you have any further questions or concerns, please don't hesitate to let me know.
